---
galaxy_info:
  author: Emrecan Altinsoy
  namespace: emrecan
  role_name: common
  description: Contains common tasks

  license: MIT

  min_ansible_version: "2.9"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: []

dependencies: []
