galaxy_info:
  author: Emrecan Altinsoy
  description: Discover current files and configuration

  license: MIT

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: []

dependencies: []
