---
# tasks file for roles/docker
# Installs Docker (Debian) or Podman (RedHat)

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  tags:
    - docker
    - install
    - service
