---
# tasks file for roles/docker
- name: Install Docker
  ansible.builtin.import_tasks:
    file: install_docker.yml
- name: Start Docker service
  ansible.builtin.import_tasks:
    file: start_docker_service.yml
