---
# Check Vault configuration
- name: Ensure user_email is defined
  ansible.builtin.assert:
    that: "user_email is defined"
    fail_msg: "user_email is not defined. See README.md for secrets.yml configuration."
- name: Ensure user_fullname is defined
  ansible.builtin.assert:
    that: "user_fullname is defined"
    fail_msg: "user_fullname is not defined. See README.md for secrets.yml configuration."
- name: Ensure user_passphrase is defined
  ansible.builtin.assert:
    that: "user_passphrase is defined"
    fail_msg: "user_passphrase is not defined. See README.md for secrets.yml configuration."
