---
# Configure GH CLI

# Debian/Ubuntu installation
- name: Install GitHub CLI if not already installed (Debian)
  become: true
  ansible.builtin.shell: |
    mkdir -p -m 755 /etc/apt/keyrings \
    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt-get update \
    && apt-get install gh -y
  args:
    executable: /bin/bash
    creates: /usr/bin/gh
  when: ansible_facts['os_family'] == "Debian"

# RedHat/Rocky installation
- name: Add GitHub CLI repository (RedHat)
  become: true
  ansible.builtin.shell: |
    dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  args:
    executable: /bin/bash
    creates: /etc/yum.repos.d/gh-cli.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Install GitHub CLI (RedHat)
  become: true
  ansible.builtin.dnf:
    name: gh
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Copy GH CLI Auth Token
  ansible.builtin.copy:
    src: files/gh_auth_token.bashrc
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/9_gh_auth_token.bashrc"
    mode: "0600"
