---
# Configure GH CLI

- name: Install GitHub CLI if not already installed
  become: true
  ansible.builtin.shell: |
    mkdir -p -m 755 /etc/apt/keyrings \
    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt-get update \
    && apt-get install gh -y
  args:
    executable: /bin/bash
    creates: /usr/bin/gh

- name: Copy GH CLI Auth Token
  ansible.builtin.copy:
    src: files/gh_auth_token.bashrc
    dest: "{{ ansible_user_dir }}/.bashrc.d/9_gh_auth_token.bashrc"
    mode: "0600"
