---
# Install ZSH

- name: Test oh-my-zsh installation
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: zsh_installation_dir

- name: Install Oh-my-ZSH
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: not zsh_installation_dir.stat.exists
