---
# tasks file for roles/devenv
- name: Install dependencies
  ansible.builtin.import_tasks:
    file: install_dependencies.yml
- name: Configure GPG
  ansible.builtin.import_tasks:
    file: configure_gpg.yml
- name: Configure SSH
  ansible.builtin.import_tasks:
    file: configure_ssh.yml
- name: Configure Git
  ansible.builtin.import_tasks:
    file: configure_git.yml
- name: Install ZSH
  ansible.builtin.import_tasks:
    file: configure_zsh.yml
- name: Install GH CLI
  ansible.builtin.import_tasks:
    file: install_gh_cli.yml
- name: Install Cargo Packages
  ansible.builtin.import_tasks:
    file: install_cargo_packages.yml
- name: Install Additional Packages
  ansible.builtin.import_tasks:
    file: install_packages.yml
- name: Stow Dotfiles
  ansible.builtin.import_tasks:
    file: stow_dotfiles.yml
